<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modelXChange" nsURI="http://www.example.org/modelXChange" nsPrefix="modelXChange">
  <eClassifiers xsi:type="ecore:EEnum" name="Waehrung">
    <eLiterals name="EUR"/>
    <eLiterals name="USD" value="1"/>
    <eLiterals name="SEK" value="2"/>
    <eLiterals name="NKR" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Konto">
    <eOperations name="ueberweisen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="zielKonto" eType="#//Konto"/>
      <eParameters name="betrag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="waehrung" lowerBound="1"
        eType="#//Waehrung"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iBAN" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bIC" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inhaber" lowerBound="1"
        upperBound="3" eType="#//Inhaber" eOpposite="#//Inhaber/konto"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inhaber">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Anschrift" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Telefonnummer" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="konto" upperBound="-1"
        eType="#//Konto" eOpposite="#//Konto/inhaber"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Buchung">
    <eOperations name="buchen"/>
    <eOperations name="validate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="betrag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="quellKonto" lowerBound="1"
        eType="#//Konto"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="zielKonto" lowerBound="1"
        eType="#//Konto"/>
  </eClassifiers>
</ecore:EPackage>
